### ISSUE TITLE
Farbschema aussuchen

### ISSUE THREAD

**Issue by VADS** [hfu-gis/gamma#8]
Guter Link dazu: https://coolors.co/app

**Comment by ManuHaa** [comment]
https://coolors.co/export/pdf/191716-ffffff-09065c-f7380b-af9bb6

**Comment by VADS** [comment]
https://coolors.co/12100e-30321c-4a4b2f-6b654b-d4df9e

**Comment by KarenJosten** [comment]
https://coolors.co/fdf8e5-00023b-e3d7a3-635b54-0d1f2d

**Comment by VADS** [comment]
Added final scheme to https://github.com/hfu-gis/gamma/wiki
